ui_print "__________________Applied patches_______________"
ui_print " "
ui_print "            *louder dual speaker"
ui_print " "
ui_print "            *better sound quality"
ui_print " "
ui_print "            *fixes low call volume"
ui_print " "
ui_print "            *better ui response"
ui_print " "
ui_print "            *better touch response"
ui_print " "
ui_print "            *memory management fixes"
ui_print " "
